# Paso 11: src/infrastructure/database/migrations/script.py.mako
"""initial_migration

Revision ID: e18e2c160be2
Revises: 
Create Date: 2026-06-18 23:04:52.301438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18e2c160be2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id_category', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name_category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_category'),
    sa.UniqueConstraint('name_category')
    )
    op.create_table('colors',
    sa.Column('id_color', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name_color', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_color'),
    sa.UniqueConstraint('name_color')
    )
    op.create_table('genders',
    sa.Column('id_gender', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name_gender', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_gender'),
    sa.UniqueConstraint('name_gender')
    )
    op.create_table('roles',
    sa.Column('id_role', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_role'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sizes',
    sa.Column('id_size', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name_size', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_size'),
    sa.UniqueConstraint('name_size')
    )
    op.create_table('suppliers',
    sa.Column('id_supplier', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name_supplier', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_supplier')
    )
    op.create_table('inventory',
    sa.Column('id_inventory', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description_inventory', sa.String(), nullable=False),
    sa.Column('utility', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('id_supplier', sa.UUID(), nullable=False),
    sa.Column('id_color', sa.UUID(), nullable=False),
    sa.Column('id_size', sa.UUID(), nullable=False),
    sa.Column('id_category', sa.UUID(), nullable=False),
    sa.Column('id_gender', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['categories.id_category'], ),
    sa.ForeignKeyConstraint(['id_color'], ['colors.id_color'], ),
    sa.ForeignKeyConstraint(['id_gender'], ['genders.id_gender'], ),
    sa.ForeignKeyConstraint(['id_size'], ['sizes.id_size'], ),
    sa.ForeignKeyConstraint(['id_supplier'], ['suppliers.id_supplier'], ),
    sa.PrimaryKeyConstraint('id_inventory')
    )
    op.create_table('users',
    sa.Column('id_user', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('id_role', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id_role'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('user')
    )
    op.create_table('inventory_photos',
    sa.Column('id_reg', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_inventory', sa.UUID(), nullable=False),
    sa.Column('url_photo', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_inventory'], ['inventory.id_inventory'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_reg')
    )
    op.create_table('movements',
    sa.Column('id_movement', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type_movement', sa.Enum('BUY', 'SELL', name='movementtype'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_supplier', sa.UUID(), nullable=True),
    sa.Column('id_inventory', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_inventory'], ['inventory.id_inventory'], ),
    sa.ForeignKeyConstraint(['id_supplier'], ['suppliers.id_supplier'], ),
    sa.PrimaryKeyConstraint('id_movement')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movements')
    op.drop_table('inventory_photos')
    op.drop_table('users')
    op.drop_table('inventory')
    op.drop_table('suppliers')
    op.drop_table('sizes')
    op.drop_table('roles')
    op.drop_table('genders')
    op.drop_table('colors')
    op.drop_table('categories')
    # ### end Alembic commands ###
